-- DO
CREATE TABLE TAB_DEPARTAMENTO
(
    COD_DEPARTAMENTO VARCHAR(5) NOT NULL,
    NOME_DEPARTAMENTO VARCHAR(50) NULL,
    CIDADE_DEPARTAMENTO VARCHAR(50) NULL,
    COD_EMPRESA VARCHAR(5) NOT NULL,
    PRIMARY KEY(COD_DEPARTAMENTO)
);
COMMIT;

-- UNDO
DROP TABLE TAB_DEPARTAMENTO;
COMMIT;