-- DO
CREATE TABLE ITENS_NOTAS
(
    NUMERO VARCHAR(5) NOT NULL,
    CODIGO VARCHAR(10) NOT NULL,
    QUANTIDADE INTEGER NULL,
    PRECO FLOAT,
    CONSTRAINT PK_TBL_ITENS_NOTAS PRIMARY KEY
    (
        NUMERO, CODIGO
    ), 
    CONSTRAINT FK_NOTAS FOREIGN KEY 
    (
        NUMERO
    ) REFERENCES NOTAS (NUMERO),
    CONSTRAINT FK_PRODUTOS FOREIGN KEY
    (
        CODIGO
    ) REFERENCES PRODUTOS (CODIGO)
);
COMMIT;

-- UNDO
DROP TABLE ITENS_NOTAS;
COMMIT;