-- DO
CREATE TABLE TABELA_DE_VENDAS
(
    NUMERO VARCHAR(5) NOT NULL,
    DATA DATE NULL,
    CPF VARCHAR(11) NOT NULL,
    MATRICULA VARCHAR(5) NOT NULL,
    IMPOSTO FLOAT NULL,
    CONSTRAINT PK_TBL_VENDAS PRIMARY KEY
    (
        NUMERO
    ),
    CONSTRAINT FK_TBL_CLIENTES FOREIGN KEY
    (
        CPF
    ) REFERENCES CLIENTES (CPF),
    CONSTRAINT FK_TBL_VENDEDORES FOREIGN KEY
    (
        MATRICULA
    ) REFERENCES VENDEDORES (MATRICULA)
);
COMMIT;

-- UNDO
DROP TABLE TABELA_DE_VENDAS;
COMMIT;