-- DO
CREATE TABLE TAB_FUNCIONARIO
(
    COD_FUNCIONARIO VARCHAR(5) NOT NULL,
    NOME_FUNCIONARIO VARCHAR(50) NULL,
    DATA_ADMISSAO DATE NULL,
    COD_DEPARTAMENTO VARCHAR(5) NOT NULL,
    CONSTRAINT TAB_FUNCIONARIO_PK PRIMARY KEY
    (
        COD_FUNCIONARIO
    )
);
COMMIT;

-- UNDO
DROP TABLE TAB_FUNCIONARIO;
COMMIT;