-- DO
ALTER TABLE TAB_DEPENDENTE
RENAME COLUMN TIPO_DEPENDENCIA TO TIPO;

ALTER TABLE TAB_DEPENDENTE
RENAME COLUMN IDADE_DEPENDENTE TO IDADE;

COMMIT;

-- UNDO

ALTER TABLE TAB_DEPENDENTE
RENAME COLUMN TIPO TO TIPO_DEPENDENCIA;

ALTER TABLE TAB_DEPENDENTE
RENAME COLUMN IDADE TO IDADE_DEPENDENTE;

COMMIT;