-- DO
CREATE TABLE TAB_PROJETO
(
    COD_PROJETO VARCHAR(5) NOT NULL,
    NOME_PROJETO VARCHAR(50) NULL,
    ORCAMENTO_PROJETO FLOAT NULL,
    DATA_INICIO_PROJETO DATE NULL,
    COD_DEPARTAMENTO VARCHAR(5) NOT NULL,
    PRIMARY KEY(COD_PROJETO)
);
COMMIT;

-- UNDO
DROP TABLE TAB_PROJETO;
COMMIT;