-- DO
INSERT INTO TAB_EMPRESA VALUES ('E0001', 'EMPRESA E0001');
INSERT INTO TAB_EMPRESA VALUES ('E0002', 'EMPRESA E0002');
COMMIT;

-- UNDO
DELETE FROM TAB_EMPRESA WHERE COD_EMPRESA = 'E0001';
DELETE FROM TAB_EMPRESA WHERE COD_EMPRESA = 'E0002';
COMMIT;