CREATE TABLE TAB_RH_DEMITIDOS (COD_FUNCIONARIO VARCHAR(5));

INSERT INTO TAB_RH_DEMITIDOS VALUES ('F0001');
INSERT INTO TAB_RH_DEMITIDOS VALUES ('F0005');
INSERT INTO TAB_RH_DEMITIDOS VALUES ('F0012');
INSERT INTO TAB_RH_DEMITIDOS VALUES ('F0022');
INSERT INTO TAB_RH_DEMITIDOS VALUES ('F0033');

COMMIT;