/*
AUTOR: William Sampaio Ramos
DATA: 09/09/2022
DESCRIÇÃO: Apagar funcionário demitidos
*/

DELETE FROM TAB_DEPENDENTE TD WHERE TD.COD_FUNCIONARIO IN
(
    SELECT TD.COD_FUNCIONARIO FROM TAB_DEPENDENTE TD
    INNER JOIN TAB_RH_DEMITIDOS TRD ON TD.COD_FUNCIONARIO = TRD.COD_FUNCIONARIO
);

DELETE FROM TAB_FUNCIONARIO TF WHERE TF.COD_FUNCIONARIO IN 
(
    SELECT TF.COD_FUNCIONARIO FROM TAB_FUNCIONARIO TF
    INNER JOIN TAB_RH_DEMITIDOS TRD ON TF.COD_FUNCIONARIO = TRD.COD_FUNCIONARIO
);

COMMIT;