
/*
AUTOR: William Sampaio Ramos
DATA: 05/09/2022
DESCRIÇÃO: Atualizar STATUS de férias na tabela vendedores com base na tabela Tabela_vendedores_Fonte
*/

-- DO/UNDO
UPDATE VENDEDORES V SET V.FERIAS =
(
    SELECT TVF.DE_FERIAS FROM TABELA_DE_VENDEDORES_FONTE TVF
    WHERE V.MATRICULA = SUBSTR(TVF.MATRICULA, 3, 3)
)
WHERE EXISTS
(
    SELECT 1 FROM TABELA_DE_VENDEDORES_FONTE TVF
    WHERE V.MATRICULA = SUBSTR(TVF.MATRICULA, 3, 3)
);

COMMIT;