-- DO
CREATE TABLE VENDEDORES
(
    MATRICULA VARCHAR(5) NOT NULL,
    NOME VARCHAR(100) NULL,
    BAIRRO VARCHAR(50) NULL,
    COMISSAO FLOAT NULL,
    DATA_ADMISSAO DATE NULL,
    FERIAS INTEGER NULL,
    PRIMARY KEY(MATRICULA)
);
COMMIT;

--UNDO
DROP TABLE VENDEDORES;
COMMIT;